# Generated by Django 3.1.4 on 2020-12-26 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Sub_title', models.CharField(max_length=100)),
                ('Text', models.TextField()),
                ('Image', models.ImageField(upload_to='images/')),
                ('Link', models.URLField(blank=True, verbose_name='Web Address')),
                ('Date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name_plural': 'Post',
            },
        ),
    ]
